import type { Meal, Vendor, Order, User } from '@/types';

export const MOCK_USER: User = {
  id: 'user-1',
  email: 'user@example.com',
  phone: '+447700900000',
  name: 'Aisha Khan',
  postcode: 'BB1 1AA',
  isVendor: false,
  createdAt: '2024-01-15T10:00:00Z',
  updatedAt: '2024-01-15T10:00:00Z',
};

export const MOCK_VENDORS: Vendor[] = [
  {
    id: 'vendor-1',
    userId: 'user-vendor-1',
    businessName: "Ammi's Kitchen",
    handle: 'ammiskitchen',
    description: 'Authentic Pakistani home cooking, just like your ammi makes. Fresh biryani and curries daily.',
    businessType: 'home_kitchen',
    avatar: '👩‍🍳',
    tags: ['halal', 'pakistani', 'indian'],
    phone: '+447700900001',
    postcode: 'BB1 2AB',
    rating: 4.9,
    reviewCount: 124,
    isVerified: true,
    isActive: true,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'vendor-2',
    userId: 'user-vendor-2',
    businessName: 'Dhaka Delights',
    handle: 'dhakadelights',
    description: 'Traditional Bangladeshi street food favourites. Biryanis, kebabs and more!',
    businessType: 'home_kitchen',
    avatar: '🍛',
    tags: ['halal', 'bangladeshi', 'street_food'],
    phone: '+447700900002',
    postcode: 'BB1 3CD',
    rating: 4.7,
    reviewCount: 89,
    isVerified: true,
    isActive: true,
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-05T10:00:00Z',
  },
  {
    id: 'vendor-3',
    userId: 'user-vendor-3',
    businessName: 'Grill Master',
    handle: 'grillmaster',
    description: 'Premium halal grills and BBQ. Burgers, steaks, and loaded fries.',
    businessType: 'shop',
    avatar: '🔥',
    tags: ['halal', 'grill', 'street_food'],
    phone: '+447700900003',
    postcode: 'BB1 4EF',
    rating: 4.8,
    reviewCount: 156,
    isVerified: true,
    isActive: true,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'vendor-4',
    userId: 'user-vendor-4',
    businessName: 'Falafel House',
    handle: 'falafelhouse',
    description: 'Fresh Middle Eastern cuisine. Falafel wraps, hummus plates, and shawarma.',
    businessType: 'popup',
    avatar: '🧆',
    tags: ['halal', 'vegetarian', 'middle_eastern'],
    phone: '+447700900004',
    postcode: 'BB1 5GH',
    rating: 4.6,
    reviewCount: 67,
    isVerified: false,
    isActive: true,
    createdAt: '2024-01-12T10:00:00Z',
    updatedAt: '2024-01-12T10:00:00Z',
  },
  {
    id: 'vendor-5',
    userId: 'user-vendor-5',
    businessName: "Naan Stop Bakery",
    handle: 'naanstop',
    description: 'Fresh naans, rotis, parathas baked daily. Plus samosas and pakoras!',
    businessType: 'home_kitchen',
    avatar: '🫓',
    tags: ['halal', 'vegetarian', 'bakery', 'indian'],
    phone: '+447700900005',
    postcode: 'BB1 6IJ',
    rating: 4.9,
    reviewCount: 203,
    isVerified: true,
    isActive: true,
    createdAt: '2024-01-08T10:00:00Z',
    updatedAt: '2024-01-08T10:00:00Z',
  },
];

const today = new Date().toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];

export const MOCK_MEALS: Meal[] = [
  {
    id: 'meal-1',
    vendorId: 'vendor-1',
    name: 'Chicken Biryani',
    description: 'Fragrant basmati rice with tender chicken, aromatic spices, and crispy onions. Served with raita.',
    emoji: '🍚',
    price: 8.99,
    dietary: ['halal'],
    spiceLevel: 2,
    stock: 12,
    maxStock: 20,
    fulfilmentType: 'both',
    prepTime: 30,
    availableDate: today,
    isActive: true,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'meal-2',
    vendorId: 'vendor-1',
    name: 'Lamb Karahi',
    description: 'Tender lamb cooked in a wok with tomatoes, green chilies, and fresh ginger. Served with naan.',
    emoji: '🍖',
    price: 10.99,
    dietary: ['halal'],
    spiceLevel: 3,
    stock: 8,
    maxStock: 15,
    fulfilmentType: 'collection',
    prepTime: 45,
    availableDate: today,
    isActive: true,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'meal-3',
    vendorId: 'vendor-2',
    name: 'Kacchi Biryani',
    description: 'Traditional Dhaka-style dum biryani with marinated mutton and potatoes.',
    emoji: '🥘',
    price: 11.99,
    dietary: ['halal'],
    spiceLevel: 2,
    stock: 6,
    maxStock: 10,
    fulfilmentType: 'both',
    prepTime: 40,
    availableDate: today,
    isActive: true,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'meal-4',
    vendorId: 'vendor-3',
    name: 'Smash Burger Meal',
    description: 'Double smashed beef patties, American cheese, special sauce. With loaded fries.',
    emoji: '🍔',
    price: 9.99,
    dietary: ['halal'],
    spiceLevel: 0,
    stock: 15,
    maxStock: 25,
    fulfilmentType: 'both',
    prepTime: 20,
    availableDate: today,
    isActive: true,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'meal-5',
    vendorId: 'vendor-4',
    name: 'Falafel Wrap',
    description: 'Crispy falafel, fresh salad, pickles, and tahini in warm pita bread.',
    emoji: '🌯',
    price: 7.49,
    dietary: ['halal', 'vegetarian', 'vegan'],
    spiceLevel: 1,
    stock: 20,
    maxStock: 30,
    fulfilmentType: 'both',
    prepTime: 15,
    availableDate: today,
    isActive: true,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'meal-6',
    vendorId: 'vendor-5',
    name: 'Samosa Pack (6)',
    description: 'Crispy vegetable samosas with mint chutney and tamarind sauce.',
    emoji: '🥟',
    price: 4.99,
    dietary: ['halal', 'vegetarian'],
    spiceLevel: 1,
    stock: 25,
    maxStock: 40,
    fulfilmentType: 'collection',
    prepTime: 10,
    availableDate: today,
    isActive: true,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'meal-7',
    vendorId: 'vendor-3',
    name: 'Chicken Wings (10)',
    description: 'Crispy fried wings with your choice of sauce: Buffalo, BBQ, or Peri Peri.',
    emoji: '🍗',
    price: 8.49,
    dietary: ['halal'],
    spiceLevel: 2,
    stock: 3,
    maxStock: 20,
    fulfilmentType: 'both',
    prepTime: 25,
    availableDate: today,
    isActive: true,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'meal-8',
    vendorId: 'vendor-1',
    name: 'Nihari Special',
    description: 'Slow-cooked beef shank in rich spiced gravy. Traditional Sunday special.',
    emoji: '🥣',
    price: 12.99,
    dietary: ['halal'],
    spiceLevel: 2,
    stock: 10,
    maxStock: 15,
    fulfilmentType: 'collection',
    prepTime: 35,
    availableDate: tomorrow,
    isActive: true,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'meal-9',
    vendorId: 'vendor-2',
    name: 'Fish Curry',
    description: 'Fresh rohu fish in Bengali mustard curry with steamed rice.',
    emoji: '🐟',
    price: 9.99,
    dietary: ['halal'],
    spiceLevel: 2,
    stock: 8,
    maxStock: 12,
    fulfilmentType: 'both',
    prepTime: 30,
    availableDate: tomorrow,
    isActive: true,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'meal-10',
    vendorId: 'vendor-4',
    name: 'Mezze Platter',
    description: 'Hummus, baba ganoush, muhammara, with warm pita and olives. Serves 2.',
    emoji: '🫒',
    price: 12.99,
    dietary: ['halal', 'vegetarian', 'vegan'],
    spiceLevel: 0,
    stock: 10,
    maxStock: 15,
    fulfilmentType: 'both',
    prepTime: 20,
    availableDate: tomorrow,
    isActive: true,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'order-001',
    userId: 'user-1',
    vendorId: 'vendor-1',
    status: 'preparing',
    fulfilmentType: 'collection',
    items: [
      {
        id: 'item-1',
        orderId: 'order-001',
        mealId: 'meal-1',
        mealName: 'Chicken Biryani',
        quantity: 2,
        unitPrice: 8.99,
        totalPrice: 17.98,
      },
    ],
    subtotal: 17.98,
    serviceFee: 0.90,
    total: 18.88,
    collectionTime: new Date(Date.now() + 3600000).toISOString(),
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'order-002',
    userId: 'user-1',
    vendorId: 'vendor-3',
    status: 'delivered',
    fulfilmentType: 'delivery',
    items: [
      {
        id: 'item-2',
        orderId: 'order-002',
        mealId: 'meal-4',
        mealName: 'Smash Burger Meal',
        quantity: 1,
        unitPrice: 9.99,
        totalPrice: 9.99,
      },
      {
        id: 'item-3',
        orderId: 'order-002',
        mealId: 'meal-7',
        mealName: 'Chicken Wings (10)',
        quantity: 1,
        unitPrice: 8.49,
        totalPrice: 8.49,
      },
    ],
    subtotal: 18.48,
    serviceFee: 0.92,
    deliveryFee: 2.50,
    total: 21.90,
    deliveryAddress: '123 Test Street, BB1 1AA',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const VENDORS_MAP = MOCK_VENDORS.reduce((acc, vendor) => {
  acc[vendor.id] = vendor;
  return acc;
}, {} as Record<string, Vendor>);

export const DIETARY_FILTERS = [
  { key: 'all', label: 'All' },
  { key: 'halal', label: '☪ Halal' },
  { key: 'vegetarian', label: '🌿 Vegetarian' },
  { key: 'vegan', label: '🌱 Vegan' },
  { key: 'gluten_free', label: '🌾 Gluten Free' },
] as const;

export const ONBOARDING_SCREENS = [
  {
    id: '1',
    title: 'Fresh halal meals from your neighbours',
    description: 'Discover homemade dishes from talented local cooks in Blackburn. Authentic recipes, made with love.',
    emoji: '🍽️',
  },
  {
    id: '2',
    title: 'Plan your week',
    description: 'Browse the 14-day schedule. Pre-order meals in advance and never miss your favourites.',
    emoji: '📅',
  },
  {
    id: '3',
    title: 'Collection or delivery',
    description: 'Pick up fresh from your local vendor, or get it delivered to your door.',
    emoji: '📍',
  },
  {
    id: '4',
    title: 'Support your community',
    description: 'Every order supports local families and keeps money in Blackburn. Eat local, support local.',
    emoji: '💚',
  },
];
